// Generated by gencpp from file cwru_msgs/cRIOSensors.msg
// DO NOT EDIT!


#ifndef CWRU_MSGS_MESSAGE_CRIOSENSORS_H
#define CWRU_MSGS_MESSAGE_CRIOSENSORS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace cwru_msgs
{
template <class ContainerAllocator>
struct cRIOSensors_
{
  typedef cRIOSensors_<ContainerAllocator> Type;

  cRIOSensors_()
    : header()
    , left_wheel_encoder(0)
    , right_wheel_encoder(0)
    , left_motor_encoder(0)
    , right_motor_encoder(0)
    , yaw_rate(0)
    , yaw_temp(0)
    , yaw_ref(0)  {
    }
  cRIOSensors_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , left_wheel_encoder(0)
    , right_wheel_encoder(0)
    , left_motor_encoder(0)
    , right_motor_encoder(0)
    , yaw_rate(0)
    , yaw_temp(0)
    , yaw_ref(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _left_wheel_encoder_type;
  _left_wheel_encoder_type left_wheel_encoder;

   typedef int32_t _right_wheel_encoder_type;
  _right_wheel_encoder_type right_wheel_encoder;

   typedef int32_t _left_motor_encoder_type;
  _left_motor_encoder_type left_motor_encoder;

   typedef int32_t _right_motor_encoder_type;
  _right_motor_encoder_type right_motor_encoder;

   typedef int16_t _yaw_rate_type;
  _yaw_rate_type yaw_rate;

   typedef int16_t _yaw_temp_type;
  _yaw_temp_type yaw_temp;

   typedef int16_t _yaw_ref_type;
  _yaw_ref_type yaw_ref;




  typedef boost::shared_ptr< ::cwru_msgs::cRIOSensors_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cwru_msgs::cRIOSensors_<ContainerAllocator> const> ConstPtr;

}; // struct cRIOSensors_

typedef ::cwru_msgs::cRIOSensors_<std::allocator<void> > cRIOSensors;

typedef boost::shared_ptr< ::cwru_msgs::cRIOSensors > cRIOSensorsPtr;
typedef boost::shared_ptr< ::cwru_msgs::cRIOSensors const> cRIOSensorsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cwru_msgs::cRIOSensors_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cwru_msgs::cRIOSensors_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cwru_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'cwru_msgs': ['/home/thomas/ros_ws/src/cwru/cwru_msgs/cwru_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cwru_msgs::cRIOSensors_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cwru_msgs::cRIOSensors_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cwru_msgs::cRIOSensors_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cwru_msgs::cRIOSensors_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cwru_msgs::cRIOSensors_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cwru_msgs::cRIOSensors_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cwru_msgs::cRIOSensors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "210acf44f8ca85255cab84f619fb4f26";
  }

  static const char* value(const ::cwru_msgs::cRIOSensors_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x210acf44f8ca8525ULL;
  static const uint64_t static_value2 = 0x5cab84f619fb4f26ULL;
};

template<class ContainerAllocator>
struct DataType< ::cwru_msgs::cRIOSensors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cwru_msgs/cRIOSensors";
  }

  static const char* value(const ::cwru_msgs::cRIOSensors_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cwru_msgs::cRIOSensors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
int32 left_wheel_encoder\n\
int32 right_wheel_encoder\n\
int32 left_motor_encoder\n\
int32 right_motor_encoder\n\
\n\
int16 yaw_rate\n\
int16 yaw_temp\n\
int16 yaw_ref\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::cwru_msgs::cRIOSensors_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cwru_msgs::cRIOSensors_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.left_wheel_encoder);
      stream.next(m.right_wheel_encoder);
      stream.next(m.left_motor_encoder);
      stream.next(m.right_motor_encoder);
      stream.next(m.yaw_rate);
      stream.next(m.yaw_temp);
      stream.next(m.yaw_ref);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct cRIOSensors_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cwru_msgs::cRIOSensors_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cwru_msgs::cRIOSensors_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "left_wheel_encoder: ";
    Printer<int32_t>::stream(s, indent + "  ", v.left_wheel_encoder);
    s << indent << "right_wheel_encoder: ";
    Printer<int32_t>::stream(s, indent + "  ", v.right_wheel_encoder);
    s << indent << "left_motor_encoder: ";
    Printer<int32_t>::stream(s, indent + "  ", v.left_motor_encoder);
    s << indent << "right_motor_encoder: ";
    Printer<int32_t>::stream(s, indent + "  ", v.right_motor_encoder);
    s << indent << "yaw_rate: ";
    Printer<int16_t>::stream(s, indent + "  ", v.yaw_rate);
    s << indent << "yaw_temp: ";
    Printer<int16_t>::stream(s, indent + "  ", v.yaw_temp);
    s << indent << "yaw_ref: ";
    Printer<int16_t>::stream(s, indent + "  ", v.yaw_ref);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CWRU_MSGS_MESSAGE_CRIOSENSORS_H
