// Generated by gencpp from file cwru_msgs/ErrorCode.msg
// DO NOT EDIT!


#ifndef CWRU_MSGS_MESSAGE_ERRORCODE_H
#define CWRU_MSGS_MESSAGE_ERRORCODE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cwru_msgs
{
template <class ContainerAllocator>
struct ErrorCode_
{
  typedef ErrorCode_<ContainerAllocator> Type;

  ErrorCode_()
    : val(0)  {
    }
  ErrorCode_(const ContainerAllocator& _alloc)
    : val(0)  {
  (void)_alloc;
    }



   typedef int32_t _val_type;
  _val_type val;


    enum { PLANNING_FAILED = -1 };
     enum { SUCCESS = 1 };
 

  typedef boost::shared_ptr< ::cwru_msgs::ErrorCode_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cwru_msgs::ErrorCode_<ContainerAllocator> const> ConstPtr;

}; // struct ErrorCode_

typedef ::cwru_msgs::ErrorCode_<std::allocator<void> > ErrorCode;

typedef boost::shared_ptr< ::cwru_msgs::ErrorCode > ErrorCodePtr;
typedef boost::shared_ptr< ::cwru_msgs::ErrorCode const> ErrorCodeConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cwru_msgs::ErrorCode_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cwru_msgs::ErrorCode_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cwru_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'cwru_msgs': ['/home/thomas/ros_ws/src/cwru/cwru_msgs/cwru_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cwru_msgs::ErrorCode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cwru_msgs::ErrorCode_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cwru_msgs::ErrorCode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cwru_msgs::ErrorCode_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cwru_msgs::ErrorCode_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cwru_msgs::ErrorCode_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cwru_msgs::ErrorCode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c82f63c84d402abe94fbefc7f5feebf6";
  }

  static const char* value(const ::cwru_msgs::ErrorCode_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc82f63c84d402abeULL;
  static const uint64_t static_value2 = 0x94fbefc7f5feebf6ULL;
};

template<class ContainerAllocator>
struct DataType< ::cwru_msgs::ErrorCode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cwru_msgs/ErrorCode";
  }

  static const char* value(const ::cwru_msgs::ErrorCode_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cwru_msgs::ErrorCode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 PLANNING_FAILED=-1\n\
int32 SUCCESS=1\n\
int32 val\n\
";
  }

  static const char* value(const ::cwru_msgs::ErrorCode_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cwru_msgs::ErrorCode_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.val);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ErrorCode_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cwru_msgs::ErrorCode_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cwru_msgs::ErrorCode_<ContainerAllocator>& v)
  {
    s << indent << "val: ";
    Printer<int32_t>::stream(s, indent + "  ", v.val);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CWRU_MSGS_MESSAGE_ERRORCODE_H
