// Generated by gencpp from file cwru_msgs/Pose.msg
// DO NOT EDIT!


#ifndef CWRU_MSGS_MESSAGE_POSE_H
#define CWRU_MSGS_MESSAGE_POSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace cwru_msgs
{
template <class ContainerAllocator>
struct Pose_
{
  typedef Pose_<ContainerAllocator> Type;

  Pose_()
    : header()
    , x(0.0)
    , y(0.0)
    , theta(0.0)
    , vel(0.0)
    , omega(0.0)
    , x_var(0.0)
    , y_var(0.0)
    , theta_var(0.0)
    , vel_var(0.0)
    , omega_var(0.0)  {
    }
  Pose_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , x(0.0)
    , y(0.0)
    , theta(0.0)
    , vel(0.0)
    , omega(0.0)
    , x_var(0.0)
    , y_var(0.0)
    , theta_var(0.0)
    , vel_var(0.0)
    , omega_var(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _theta_type;
  _theta_type theta;

   typedef float _vel_type;
  _vel_type vel;

   typedef float _omega_type;
  _omega_type omega;

   typedef float _x_var_type;
  _x_var_type x_var;

   typedef float _y_var_type;
  _y_var_type y_var;

   typedef float _theta_var_type;
  _theta_var_type theta_var;

   typedef float _vel_var_type;
  _vel_var_type vel_var;

   typedef float _omega_var_type;
  _omega_var_type omega_var;




  typedef boost::shared_ptr< ::cwru_msgs::Pose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cwru_msgs::Pose_<ContainerAllocator> const> ConstPtr;

}; // struct Pose_

typedef ::cwru_msgs::Pose_<std::allocator<void> > Pose;

typedef boost::shared_ptr< ::cwru_msgs::Pose > PosePtr;
typedef boost::shared_ptr< ::cwru_msgs::Pose const> PoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cwru_msgs::Pose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cwru_msgs::Pose_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cwru_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'cwru_msgs': ['/home/thomas/ros_ws/src/cwru/cwru_msgs/cwru_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cwru_msgs::Pose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cwru_msgs::Pose_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cwru_msgs::Pose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cwru_msgs::Pose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cwru_msgs::Pose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cwru_msgs::Pose_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cwru_msgs::Pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7ce3d88c4d07be05d54abf722834318f";
  }

  static const char* value(const ::cwru_msgs::Pose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7ce3d88c4d07be05ULL;
  static const uint64_t static_value2 = 0xd54abf722834318fULL;
};

template<class ContainerAllocator>
struct DataType< ::cwru_msgs::Pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cwru_msgs/Pose";
  }

  static const char* value(const ::cwru_msgs::Pose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cwru_msgs::Pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float32 x\n\
float32 y\n\
float32 theta\n\
float32 vel\n\
float32 omega\n\
float32 x_var\n\
float32 y_var\n\
float32 theta_var\n\
float32 vel_var\n\
float32 omega_var\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::cwru_msgs::Pose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cwru_msgs::Pose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.theta);
      stream.next(m.vel);
      stream.next(m.omega);
      stream.next(m.x_var);
      stream.next(m.y_var);
      stream.next(m.theta_var);
      stream.next(m.vel_var);
      stream.next(m.omega_var);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Pose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cwru_msgs::Pose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cwru_msgs::Pose_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "theta: ";
    Printer<float>::stream(s, indent + "  ", v.theta);
    s << indent << "vel: ";
    Printer<float>::stream(s, indent + "  ", v.vel);
    s << indent << "omega: ";
    Printer<float>::stream(s, indent + "  ", v.omega);
    s << indent << "x_var: ";
    Printer<float>::stream(s, indent + "  ", v.x_var);
    s << indent << "y_var: ";
    Printer<float>::stream(s, indent + "  ", v.y_var);
    s << indent << "theta_var: ";
    Printer<float>::stream(s, indent + "  ", v.theta_var);
    s << indent << "vel_var: ";
    Printer<float>::stream(s, indent + "  ", v.vel_var);
    s << indent << "omega_var: ";
    Printer<float>::stream(s, indent + "  ", v.omega_var);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CWRU_MSGS_MESSAGE_POSE_H
