obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[-0.75, -0.4], [0.75, -0.4], [0.75, 0.4], [-0.75, 0.4]]
#robot_radius: ir_of_robot
inflation_radius: 0.75

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: lidar_link, data_type: LaserScan, topic: /sensor_msgs/LaserScan, marking: true, clearing: true}
