obstacle_range: 5.0
raytrace_range: 6.0
footprint: [[-0.5, -0.45], [0.75, -0.45], [0.75, 0.45], [-0.5, 0.45]]
#robot_radius: ir_of_robot
inflation_radius: 3.0

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: lidar_link, data_type: LaserScan, topic: /sensor_msgs/LaserScan, marking: true, clearing: true}
